import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// RLE (Right-to-Left Embedding) character for Arabic text
const RLE = "\u202B";

interface SchoolInfo {
  nameEn: string;
  nameAr: string;
  address?: string;
  phone?: string;
  email?: string;
}

interface SchoolReportData {
  totalStudents: number;
  totalTeachers: number;
  totalClasses: number;
  averageAttendance: number;
  averageGrade: number;
  topPerformers: Array<{
    id: string;
    name: string;
    class: string;
    averageGrade: number;
  }>;
  needsAttention: Array<{
    id: string;
    name: string;
    class: string;
    attendanceRate: number;
    averageGrade: number;
  }>;
}

interface SchoolReportPDFProps {
  data: SchoolReportData;
  schoolInfo: SchoolInfo;
  locale: "en" | "ar";
}

// Register Amiri font using base64
let fontRegistered = false;

export async function registerAmiriFont() {
  if (fontRegistered) return;
  
  try {
    const { AMIRI_REGULAR_BASE64 } = await import("@/lib/pdf/fonts/amiri");
    
    // Register font using data URI - react-pdf supports this format
    Font.register({
      family: "Amiri",
      src: `data:font/truetype;charset=utf-8;base64,${AMIRI_REGULAR_BASE64}`,
    });
    
    fontRegistered = true;
    if (process.env.NODE_ENV === "development") {
      console.log("Amiri font registered successfully");
    }
  } catch (error) {
    console.error("Failed to register Amiri font:", error);
    // Don't throw - allow fallback to Helvetica
    fontRegistered = false;
  }
}

// Helper function to add RLE for Arabic text
const arabicText = (text: string): string => {
  return RLE + text;
};

const createStyles = (isArabic: boolean) => {
  const fontFamily = isArabic && fontRegistered ? "Amiri" : "Helvetica";
  
  return StyleSheet.create({
    page: {
      padding: 40,
      fontFamily: fontFamily,
      direction: isArabic ? "rtl" : "ltr",
    },
    header: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#1e40af",
      marginBottom: 10,
      textAlign: isArabic ? "right" : "left",
    },
    contact: {
      fontSize: 10,
      color: "#6b7280",
      marginBottom: 20,
      textAlign: isArabic ? "right" : "left",
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "bold",
      marginTop: 20,
      marginBottom: 10,
      color: "#1f2937",
      textAlign: isArabic ? "right" : "left",
    },
    table: {
      display: "flex",
      flexDirection: "column",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: "#e5e7eb",
    },
    tableRow: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: "#e5e7eb",
    },
    tableHeader: {
      backgroundColor: "#3b82f6",
      color: "white",
      fontWeight: "bold",
      fontSize: 12,
      padding: 8,
    },
    tableCell: {
      fontSize: 10,
      padding: 8,
      flex: 1,
    },
    tableCellValue: {
      fontSize: 10,
      padding: 8,
      width: "30%",
      textAlign: "right",
    },
    footer: {
      fontSize: 9,
      color: "#6b7280",
      textAlign: "center",
      marginTop: 30,
    },
    date: {
      fontSize: 10,
      marginBottom: 10,
      textAlign: isArabic ? "right" : "left",
    },
  });
};

export function SchoolReportPDF({
  data,
  schoolInfo,
  locale,
}: SchoolReportPDFProps) {
  const isArabic = locale === "ar";
  const styles = createStyles(isArabic);

  const currentDate = new Date().toLocaleDateString(
    isArabic ? "ar-SA" : "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );

  const labels = isArabic
    ? {
        title: "تقرير المدرسة الشامل",
        date: "التاريخ",
        summary: "الملخص",
        totalStudents: "إجمالي الطلاب",
        totalTeachers: "إجمالي المعلمين",
        totalClasses: "إجمالي الفصول",
        averageAttendance: "متوسط الحضور",
        averageGrade: "متوسط الدرجات",
        topPerformers: "أفضل الأداء",
        needsAttention: "يحتاج إلى انتباه",
        name: "الاسم",
        class: "الفصل",
        grade: "الدرجة",
        attendance: "الحضور",
        footer: "تم إنشاء هذا التقرير تلقائياً من نظام إدارة المدرسة",
      }
    : {
        title: "Comprehensive School Report",
        date: "Date",
        summary: "Summary",
        totalStudents: "Total Students",
        totalTeachers: "Total Teachers",
        totalClasses: "Total Classes",
        averageAttendance: "Average Attendance",
        averageGrade: "Average Grade",
        topPerformers: "Top Performers",
        needsAttention: "Needs Attention",
        name: "Name",
        class: "Class",
        grade: "Grade",
        attendance: "Attendance",
        footer: "This report was automatically generated by the school management system",
      };

  const formatText = (text: string): string => {
    return isArabic ? arabicText(text) : text;
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <Text style={styles.header}>
          {formatText(isArabic ? schoolInfo.nameAr : schoolInfo.nameEn)}
        </Text>

        {/* Contact Info */}
        {(schoolInfo.address || schoolInfo.phone || schoolInfo.email) && (
          <View style={styles.contact}>
            {schoolInfo.address && (
              <Text style={styles.contact}>
                {formatText(schoolInfo.address)}
              </Text>
            )}
            {schoolInfo.phone && (
              <Text style={styles.contact}>
                {formatText(schoolInfo.phone)}
              </Text>
            )}
            {schoolInfo.email && (
              <Text style={styles.contact}>
                {formatText(schoolInfo.email)}
              </Text>
            )}
          </View>
        )}

        {/* Date */}
        <Text style={styles.date}>
          {formatText(`${labels.date}: ${currentDate}`)}
        </Text>

        {/* Summary Section */}
        <Text style={styles.sectionTitle}>{formatText(labels.summary)}</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <View style={[styles.tableCell, styles.tableHeader]}>
              <Text>{formatText(labels.totalStudents)}</Text>
            </View>
            <View style={[styles.tableCellValue, styles.tableHeader]}>
              <Text>{data.totalStudents}</Text>
            </View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCell}>
              <Text>{formatText(labels.totalTeachers)}</Text>
            </View>
            <View style={styles.tableCellValue}>
              <Text>{data.totalTeachers}</Text>
            </View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCell}>
              <Text>{formatText(labels.totalClasses)}</Text>
            </View>
            <View style={styles.tableCellValue}>
              <Text>{data.totalClasses}</Text>
            </View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCell}>
              <Text>{formatText(labels.averageAttendance)}</Text>
            </View>
            <View style={styles.tableCellValue}>
              <Text>{data.averageAttendance}%</Text>
            </View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCell}>
              <Text>{formatText(labels.averageGrade)}</Text>
            </View>
            <View style={styles.tableCellValue}>
              <Text>{data.averageGrade}%</Text>
            </View>
          </View>
        </View>

        {/* Top Performers */}
        {data.topPerformers.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>
              {formatText(labels.topPerformers)}
            </Text>
            <View style={styles.table}>
              <View style={styles.tableRow}>
                <View style={[styles.tableCell, styles.tableHeader]}>
                  <Text>{formatText(labels.name)}</Text>
                </View>
                <View style={[styles.tableCell, styles.tableHeader]}>
                  <Text>{formatText(labels.class)}</Text>
                </View>
                <View style={[styles.tableCellValue, styles.tableHeader]}>
                  <Text>{formatText(labels.grade)}</Text>
                </View>
              </View>
              {data.topPerformers.map((student, index) => (
                <View key={student.id} style={styles.tableRow}>
                  <View style={styles.tableCell}>
                    <Text>{formatText(student.name)}</Text>
                  </View>
                  <View style={styles.tableCell}>
                    <Text>{formatText(student.class)}</Text>
                  </View>
                  <View style={styles.tableCellValue}>
                    <Text>{student.averageGrade}%</Text>
                  </View>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Needs Attention */}
        {data.needsAttention.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>
              {formatText(labels.needsAttention)}
            </Text>
            <View style={styles.table}>
              <View style={styles.tableRow}>
                <View style={[styles.tableCell, styles.tableHeader]}>
                  <Text>{formatText(labels.name)}</Text>
                </View>
                <View style={[styles.tableCell, styles.tableHeader]}>
                  <Text>{formatText(labels.class)}</Text>
                </View>
                <View style={[styles.tableCell, styles.tableHeader]}>
                  <Text>{formatText(labels.attendance)}</Text>
                </View>
                <View style={[styles.tableCellValue, styles.tableHeader]}>
                  <Text>{formatText(labels.grade)}</Text>
                </View>
              </View>
              {data.needsAttention.map((student) => (
                <View key={student.id} style={styles.tableRow}>
                  <View style={styles.tableCell}>
                    <Text>{formatText(student.name)}</Text>
                  </View>
                  <View style={styles.tableCell}>
                    <Text>{formatText(student.class)}</Text>
                  </View>
                  <View style={styles.tableCell}>
                    <Text>{student.attendanceRate.toFixed(1)}%</Text>
                  </View>
                  <View style={styles.tableCellValue}>
                    <Text>{student.averageGrade.toFixed(1)}%</Text>
                  </View>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Footer */}
        <Text style={styles.footer}>{formatText(labels.footer)}</Text>
      </Page>
    </Document>
  );
}

